version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dusanmalusev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    networks:
      - net
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - net
    environment:
        PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "test123!"
        PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    ports:
        - '8000:80'
    depends_on:
        - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
  redis:
    image: redis:6-alpine
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
    networks:
      - net
  redislabs:
    image: redislabs/redisinsight:1.8.3
    ports:
      -  '8001:8001'
    depends_on:
      - redis
    networks:
      - net
networks:
  net:
    driver: bridge
volumes:
  postgres:
  pgadmin:
  redis:
